import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/ui/header";

const beausiteClassic = localFont({
  src: [
    {
      path: "./fonts/BeausiteClassicSemibold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/BeausiteClassicMedium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/BeausiteClassicRegular.otf",
      weight: "400",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${beausiteClassic.className} antialiased bg-bgGradient`}
      >
        <main className="w-full mx-auto">
          <Header />
        </main>
        {children}
      </body>
    </html>
  );
}
