import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";

const beausiteClassic = localFont({
  src: [
    {
      path: "./fonts/BeausiteClassicSemibold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/BeausiteClassicMedium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/BeausiteClassicRegular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/BeausiteClassicBold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${beausiteClassic.className} antialiased bg-bgGradient scroll-smooth`}
      >
        <Header />
        <main className="w-full h-full mx-auto">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
